name: Run pytests

on: [push]

jobs:
  build-linux:
    runs-on: ubuntu-latest
    permissions:
        contents: write
    steps:
    - uses: actions/checkout@v3
    - name: Set up Python 3.12
      uses: actions/setup-python@v3
      with:
        python-version: '3.12'
        cache: 'pip'
    - name: Install dependencies
      run: |
        pip install requirements.txt
        pip install .
    - name: Run pre-commit
      run: |
        pre-commit run --all-files
    - name: Run pytest
      run: |
        pytest test