name: Run pytests

on: [push]

jobs:
  build-linux:
    runs-on: ubuntu-latest
    permissions:
        contents: write
    steps:
    - uses: actions/checkout@v3
    - name: Set up Python 3.12
      uses: actions/setup-python@v3
      with:
        python-version: '3.12'
    - name: Add conda to system path
      run: |
        # $CONDA is an environment variable pointing to the root of the miniconda directory
        echo $CONDA/bin >> $GITHUB_PATH
    - name: Install dependencies
      run: |
        conda env update --file environment.yml --name data-traps-core-env
    - name: Run pre-commit
      run: |
        conda run -n data-traps-core-env pre-commit run --all-files
    - name: Test with pytest
      run: |
        conda run -n data-traps-core-env pytest test
    - name: Install dependencies
      run: |
        conda run -n data-traps-core-env pip install .
    - name: Run pytest
      run: |
        pytest test